<a href="https://colab.research.google.com/github/yoanaFoteva/Matrix-Computation/blob/main/Courseworks/Matrix_Spectrum_and_ODEs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Computing the matrix spectrum and solving linear systems of differential equations

We are given the following matrix:

$A = \begin{bmatrix}
1 & 2 & 3 \\
2 & 1 & 4 \\
3 & 4 & 1
\end{bmatrix}$

Tasks:
1.   Compute the spectrum (eigenvalues and eigenvectors)
2.   Solve linear systems of differential equations of the form:

$\dot{\mathbf{x}} = A \mathbf{x}, \quad \mathbf{x} =
\begin{bmatrix} x_1(t) \\ x_2(t) \end{bmatrix}$

and find the general solution.

## 1. Compute the spectrum

In [ ]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [2, 1, 4],
    [3, 4, 1]
])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[ 7.07467358 -0.88679099 -3.1878826 ]

Eigenvectors (column i = eigenvector for eigenvalue i):
[[ 0.50578521  0.82403773 -0.25523155]
 [ 0.58437383 -0.54492509 -0.60130182]
 [ 0.63457746 -0.15497893  0.75716113]]


## 2. Solve linear systems of differential equations

We consider systems of the form:

$\dot{\mathbf{x}} = A \mathbf{x}, \quad \mathbf{x}(t) = \begin{bmatrix} x_1(t) \\ x_2(t) \end{bmatrix}$

Example systems
\begin{cases}
\dot{x}_1 = 2 x_1 + x_2 \\
\dot{x}_2 = 3 x_1 + 4 x_2
\end{cases}

\begin{cases}
\dot{x}_1 = 2 x_1 - 6 x_2 \\
\dot{x}_2 = 3 x_1 + 4 x_2
\end{cases}


In [ ]:
import sympy as sp

def solve_linear_system(A):
    t = sp.symbols('t')
    n = A.shape[0]
    X = sp.Matrix([sp.Function(f"x{i+1}")(t) for i in range(n)])
    system = X.diff(t) - A * X
    sol = sp.dsolve(system)

    print("\nGeneral solution for system X' = A X:")
    for eq in sol:
        sp.pprint(eq)
    print("\n" + "-"*50 + "\n")

    return None

A1 = sp.Matrix([
    [2, 1],
    [3, 4]
])

A2 = sp.Matrix([
    [2, -6],
    [3,  4]
])

solve_linear_system(A1)
solve_linear_system(A2)


General solution for system X' = A X:
                      5⋅t
              t   C₂⋅ℯ   
x₁(t) = - C₁⋅ℯ  + ───────
                     3   
            t       5⋅t
x₂(t) = C₁⋅ℯ  + C₂⋅ℯ   

--------------------------------------------------


General solution for system X' = A X:
          ⎛C₁   √17⋅C₂⎞  3⋅t              ⎛√17⋅C₁   C₂⎞  3⋅t           
x₁(t) = - ⎜── + ──────⎟⋅ℯ   ⋅cos(√17⋅t) - ⎜────── - ──⎟⋅ℯ   ⋅sin(√17⋅t)
          ⎝3      3   ⎠                   ⎝  3      3 ⎠                
            3⋅t                  3⋅t           
x₂(t) = C₁⋅ℯ   ⋅cos(√17⋅t) - C₂⋅ℯ   ⋅sin(√17⋅t)

--------------------------------------------------



Example systems:  


\begin{aligned}
\begin{cases}
\dot{x}_1 = x_1 \\
\dot{x}_2 = 6 x_2 - 7 x_3 + 3 x_4\\
\dot{x}_3 = 3 x_3 - x_4\\
\dot{x}_4 = -4 x_2 + 9 x_3 - 3x_4
\end{cases}
\qquad
\begin{cases}
\dot{x}_1 = -2 x_1 - 6 x_2 \\
\dot{x}_2 = 3 x_1 + 4 x_2
\end{cases}
\qquad
\begin{cases}
\dot{x}_1 = 3 x_1 - 4 x_2 - x_3 \\
\dot{x}_2 = - x_2 - x_3\\
\dot{x}_3 = -4 x_2 - 2 x_3
\end{cases}
\end{aligned}


In [ ]:
A3 = sp.Matrix([
    [1, 0, 0, 0],
    [0, 6, -7, 3],
    [0, 0, 3, -1],
    [0, -4, 9, -3]
])

A4 = sp.Matrix([
    [-2, -6],
    [3,  4]
])

A5 = sp.Matrix([
    [3, -4, -1],
    [0, -1, -1],
    [0, -4, 2]
])

solve_linear_system(A3)
solve_linear_system(A4)
solve_linear_system(A5)


General solution for system X' = A X:
            t
x₁(t) = C₁⋅ℯ 
              2  2⋅t                    2⋅t                       2⋅t
x₂(t) = 2⋅C₂⋅t ⋅ℯ    + t⋅(4⋅C₂ + 4⋅C₄)⋅ℯ    + (C₂ + 4⋅C₃ + 4⋅C₄)⋅ℯ   
              2  2⋅t         2⋅t           2⋅t
x₃(t) = 2⋅C₂⋅t ⋅ℯ    + 4⋅C₃⋅ℯ    + 4⋅C₄⋅t⋅ℯ   
              2  2⋅t                    2⋅t                  2⋅t
x₄(t) = 2⋅C₂⋅t ⋅ℯ    - t⋅(4⋅C₂ - 4⋅C₄)⋅ℯ    + (4⋅C₃ - 4⋅C₄)⋅ℯ   

--------------------------------------------------


General solution for system X' = A X:
                     t                       t         
x₁(t) = - (C₁ - C₂)⋅ℯ ⋅sin(3⋅t) - (C₁ + C₂)⋅ℯ ⋅cos(3⋅t)
            t                t         
x₂(t) = C₁⋅ℯ ⋅cos(3⋅t) - C₂⋅ℯ ⋅sin(3⋅t)

--------------------------------------------------


General solution for system X' = A X:
            -2⋅t       3⋅t
x₁(t) = C₁⋅ℯ     + C₂⋅ℯ   
                       3⋅t
            -2⋅t   C₃⋅ℯ   
x₂(t) = C₁⋅ℯ     - ───────
                      4   
            -2⋅t       3⋅t
x₃(t